import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Metadata } from 'next'
import { SITE_URL } from '@/lib/config'

export const metadata: Metadata = {
  title: { absolute: 'Terms of Service | Free Online Tools' },
  description: 'Terms of Service for Free Online Tools at onlinefreetools.online. Read about acceptable use, tool output disclaimers, and intellectual property.',
  alternates: {
    canonical: `${SITE_URL}/terms`,
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8 italic">Last Updated: July 2026</p>

        <div className="prose prose-invert max-w-none space-y-6 text-foreground">
          <section>
            <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing and using Free Online Tools at onlinefreetools.online (&quot;the Site&quot;), you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the Site. These terms apply to all tools on the Site, including our developer utilities (JSON Formatter, JWT Decoder, Regex Tester, SQL Formatter, Base64 Encoder, and others), calculators (BMI Calculator, Loan Calculator, Mortgage Calculator, and others), document tools (Word Counter, Markdown Editor, Image Compressor, and others), and general utilities (Password Generator, Dice Roller, Coin Flipper, and others).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">2. Description of Services</h2>
            <p className="text-muted-foreground">
              Free Online Tools provides a collection of browser-based utilities organized into four categories: Developer Tools, Document &amp; Media tools, Calculators, and Utilities. Most tools process your data entirely within your web browser — your inputs and outputs never leave your device. The one exception is our QR Code Generator, which uses a third-party API (api.qrserver.com) to render QR code images; any text or URL you encode is transmitted to that external service during generation. All other tools, including the JSON Formatter, Hash Generator, Image Compressor, Password Generator, and all calculators, run locally in your browser.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">3. Use License</h2>
            <p className="text-muted-foreground">
              You may use the tools and output generated by Free Online Tools for personal or commercial purposes, subject to these terms and applicable laws. You are welcome to use generated UUIDs, formatted JSON, compressed images, QR codes, hashed values, and any other tool output in your projects, applications, documents, and creative work without restriction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">4. Tool Accuracy and Limitations</h2>
            <p className="text-muted-foreground">
              While we test our tools thoroughly, no software is guaranteed to be error-free. Tool outputs may vary depending on input data, browser configuration, and other factors. Specifically:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Our <strong>BMI Calculator</strong> provides general health estimates and is not a substitute for professional medical advice.</li>
              <li>Our <strong>Loan Calculator</strong> and <strong>Mortgage Calculator</strong> produce estimates based on the values you enter. Actual loan terms may differ based on your credit, lender fees, and other factors.</li>
              <li>Our <strong>Discount Calculator</strong> and <strong>Tip Calculator</strong> compute values based on the numbers you provide — verify important financial decisions independently.</li>
              <li>Our <strong>Hash Generator</strong> produces standard hash digests but should not be used as the sole method for password storage in production systems; use dedicated libraries like bcrypt instead.</li>
              <li>Our <strong>Image Compressor</strong> reduces file sizes using browser-based processing; results depend on the original image format and content.</li>
            </ul>
            <p className="text-muted-foreground mt-4">
              We recommend verifying important results through alternative methods. We are not liable for any loss or damage arising from the use or inability to use any tool on this Site.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">5. No Professional Advice</h2>
            <p className="text-muted-foreground">
              The tools and content on this Site are not a substitute for professional advice. Do not rely solely on the BMI Calculator for medical decisions, the Loan or Mortgage Calculators for financial commitments, or any tool output for legal, medical, or financial decisions without consulting a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">6. Limitations</h2>
            <p className="text-muted-foreground">
              In no event shall Free Online Tools, its operator, or affiliates be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your access to, use of, or inability to use this Site or any tools provided herein. This includes, but is not limited to, damages for loss of profits, data, or other intangible losses.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">7. External Links and Third-Party Services</h2>
            <p className="text-muted-foreground">
              This Site may contain links to external websites or use third-party services. Our QR Code Generator uses the api.qrserver.com service for image rendering. We are not responsible for the content, privacy practices, or accuracy of any third-party websites or services. The inclusion of any link does not imply endorsement by us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">8. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We may revise these terms at any time by updating this page. Continued use of the website after changes are posted means you accept the updated terms. We recommend reviewing this page periodically.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">9. Governing Law</h2>
            <p className="text-muted-foreground">
              These terms are governed by applicable law. Any disputes arising from these terms or your use of the Site shall be resolved in the appropriate courts.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">10. Contact Information</h2>
            <p className="text-muted-foreground">
              For questions about these Terms of Service, contact us at <a href="mailto:onlinefreetools@zohomail.com" className="text-primary hover:underline">onlinefreetools@zohomail.com</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  )
}
