import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Free Online Tools',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-invert max-w-none space-y-6 text-foreground">
          <section>
            <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By using Free Online Tools, you agree to comply with these terms and conditions. If you do not agree with any part of these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">2. Use License</h2>
            <p className="text-muted-foreground">
              You may use the content and output generated by Free Online Tools for personal or commercial purposes, subject to these terms and applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">3. Disclaimer</h2>
            <p className="text-muted-foreground">
              The tools and information provided on this site are offered "as is" without warranties of any kind. We do not guarantee that tool results are error-free or suitable for every use case.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">4. Limitations</h2>
            <p className="text-muted-foreground">
              In no event shall Free Online Tools or its operators be liable for any loss or damage arising from the use of the site, including data loss or business interruption.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">5. Accuracy of Materials</h2>
            <p className="text-muted-foreground">
              We aim to keep the website accurate and up to date, but we do not promise that all tool outputs, descriptions, or instructions are always complete or current.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">6. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We may revise these terms at any time. Continued use of the website after changes are posted means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">7. Governing Law</h2>
            <p className="text-muted-foreground">
              These terms are governed by the laws of the jurisdiction where the website operator is based.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">8. Contact Information</h2>
            <p className="text-muted-foreground">
              For questions about these terms, contact us at <a href="mailto:onlinefreetools@zohomail.com" className="text-primary hover:underline">onlinefreetools@zohomail.com</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  )
}
